name: rm_front_end
description: Register Machine Simulator.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  archive: ^3.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_markdown: ^0.6.14
  http: ^0.13.5
  markdown: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: monospace
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic
